### PR TITLE
Upstreaming changes required by the Winit keyboard rework

### PR DESCRIPTION
**Pull request by maroider**
If you want me to split this out into separate PRs per logical change, I can do that, but each commit here should hopefully be self-contained. Of all these changes, the only one that's probably *technically* necessary is the one adding a couple of functions and a type alias. The changes required for some older versions of Ubuntu might also benefit from some de-duplication, but I've refrained from doing that for now.

### CODE REVIEW

**Comment by francesca64** [comment]
I'm surprised you found this repo! This is great, but I think it'd be a good idea for me to transfer this repo to rust-windowing; do you agree?

**Comment by maroider** [comment]
> I'm surprised you found this repo!

I can't even remember how I found it, haha.

> This is great, but I think it'd be a good idea for me to transfer this repo to rust-windowing; do you agree?

Sure, that sounds good to me.

**Comment by francesca64** [comment]
Done; feel free to change the `authors` in Cargo.toml to not be fran-centric, since I'm fran-kly not the original author of this code anyway.

Also feel free to merge this (and do literally anything you want in general), since I'm not really in a position to maintain this anymore.

**Comment by madsmtm** [comment]
Would you be willing to add @maroider to the list of maintainers on [crates.io](https://crates.io/crates/xkbcommon-dl), then?

**Comment by francesca64** [comment]
@madsmtm invites sent!

**Pull request merged**
