### PR TITLE
Don't expose `once_cell` publically

### LINKED ISSUE #12: Don't expose `once_cell` in the public API
Requires https://github.com/elinorbgr/dlib/pull/21 and new dlib release.

### PR DESCRIPTION
**Pull request by kchibisov**
Fixes #12.

r @notgull

--

I wasn't sure why I needed a dlib update in the first place though.

### CODE REVIEW

**Review by notgull — CHANGES_REQUESTED** [review]
It would be nice if the error message was somehow propagated, since it may be useful in determining how loading this library failed.

**Comment by kchibisov** [comment]
Hm, it's propagated via the `log`, but I don't think we should use `log` in the first place?

**Review by notgull — APPROVED** [review]
If it's logged, then I have no complaints. Looks good to me!

**Comment by notgull** [comment]
> I wasn't sure why I needed a dlib update in the first place though.

The update was so that expressions could be used in the place of the library handle, see elinorbgr/dlib#21

**Comment by kchibisov** [comment]
I think you could use it in the `ffi_dispatch!`, but we don't use `ffi_dispatch` downstream...

**Pull request merged**
